// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCt88ZOpr4wK8iLb9lX5IFDueIBgTgdMGA",
      authDomain: "edupulsemilan.firebaseapp.com",
      projectId: "edupulsemilan",
      storageBucket: "edupulsemilan.firebasestorage.app",
      messagingSenderId: "685157106296",
      appId: "1:685157106296:web:24c54cb44852099bdd238d",
      measurementId: "G-N7WWH7PMKN");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt88ZOpr4wK8iLb9lX5IFDueIBgTgdMGA',
    appId: '1:685157106296:android:88f553f7e4faf7a0dd238d',
    messagingSenderId: '685157106296',
    projectId: 'edupulsemilan',
    storageBucket: 'edupulse-a9205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_AgBnTLzLOdZPHLT_nyGD3tMVQSnbkA',
    appId: '1:489376848429:ios:6ed70f678126c2477b76a4',
    messagingSenderId: '489376848429',
    projectId: 'edupulse-a9205',
    storageBucket: 'edupulse-a9205.appspot.com',
    iosBundleId: 'com.example.responsivedashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4_AgBnTLzLOdZPHLT_nyGD3tMVQSnbkA',
    appId: '1:489376848429:ios:6ed70f678126c2477b76a4',
    messagingSenderId: '489376848429',
    projectId: 'edupulse-a9205',
    storageBucket: 'edupulse-a9205.appspot.com',
    iosBundleId: 'com.example.responsivedashboard',
  );
}
