// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      // apiKey: 'AIzaSyC6NEh-1YAIRHYpArBtRS9LXJzJ8llYrMg',
      // appId: '1:489376848429:web:9edc2ea53f0de6fa7b76a4',
      // messagingSenderId: '489376848429',
      // projectId: 'edupulse-a9205',
      // authDomain: 'edupulse-a9205.firebaseapp.com',
      // storageBucket: 'edupulse-a9205.appspot.com',
      // measurementId: 'G-WJJXE61BBY',
      apiKey: "AIzaSyDipGtXqmwN1gX1r7WxQS4mO0nczzxEFx8",
      authDomain: "bordaparivar-85e13.firebaseapp.com",
      projectId: "bordaparivar-85e13",
      storageBucket: "bordaparivar-85e13.appspot.com",
      messagingSenderId: "862823786092",
      appId: "1:862823786092:web:b50f311de7461e95c1da49",
      measurementId: "G-PX272LXVD8");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVr0kHx8M8DC4NjH7XtqUPjrIsrMmck_s',
    appId: '1:489376848429:android:74a1e00fffd07b367b76a4',
    messagingSenderId: '489376848429',
    projectId: 'edupulse-a9205',
    storageBucket: 'edupulse-a9205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_AgBnTLzLOdZPHLT_nyGD3tMVQSnbkA',
    appId: '1:489376848429:ios:6ed70f678126c2477b76a4',
    messagingSenderId: '489376848429',
    projectId: 'edupulse-a9205',
    storageBucket: 'edupulse-a9205.appspot.com',
    iosBundleId: 'com.example.responsivedashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4_AgBnTLzLOdZPHLT_nyGD3tMVQSnbkA',
    appId: '1:489376848429:ios:6ed70f678126c2477b76a4',
    messagingSenderId: '489376848429',
    projectId: 'edupulse-a9205',
    storageBucket: 'edupulse-a9205.appspot.com',
    iosBundleId: 'com.example.responsivedashboard',
  );
}
